# Create the image 'base'
FROM alpine:latest AS base
RUN apk --no-cache add terraform
RUN apk --no-cache add py2-pip groff less &&\
    pip install awscli

# Tests
FROM base AS test
# There is no jq
RUN apk --no-cache add jq
RUN terraform --version
RUN ldd $(which jq)
RUN aws help

# Save only the image
FROM base
